import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import devIlustration from '../../public/images/profile/ilustração-dev.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <AnimatedText
                text="Olá Mundo!"
                className="!text-6xl !text-left"
              ></AnimatedText>
              <p className="my-4 text-base font-medium text-3xl">
                Meu nome é Jonas Humberto, e sou estudante de desenvolvimento
                web, com foco no front-end.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={'_blank'}
                  download={true}
                  className="flex items-center bg-dark text-white p-2.5 px-6 rounded-lg text-lg font-bold hover:bg-white hover:text-black border-2 border-solid border-transparent hover:border-dark 
                  
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                >
                  Curriculo <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  href="mailto:jonas.99858439@gmail.com"
                  target={'_blank'}
                  className="text-lg font-bold ml-4 text-red-600 underline capitalize hover:text-red-800"
                >
                  Contato
                </Link>
              </div>
            </div>

            <div className="w-1/2">
              <Image
                src={devIlustration}
                alt="Ilustração de um programador"
                className="w-full h-auto"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
