import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import devIlustration from '../../public/images/profile/ilustração-dev.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full sm:flex-col ">
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Olá Mundo!"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              ></AnimatedText>
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Meu nome é Jonas Humberto, e sou estudante de desenvolvimento
                web, com foco no front-end.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target={'_blank'}
                  download={true}
                  className="flex items-center bg-dark text-white p-2.5 px-6 rounded-lg text-lg font-bold hover:bg-white hover:text-black border-2 border-solid border-transparent hover:border-dark 
                  
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  Curriculo <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  href="mailto:jonas.99858439@gmail.com"
                  target={'_blank'}
                  className="text-lg font-bold ml-4 text-red-600 underline capitalize hover:text-red-800 md:text-base"
                >
                  Contato
                </Link>
              </div>
            </div>

            <div className="w-1/2">
              <Image
                src={devIlustration}
                alt="Ilustração de um programador"
                className="w-full h-auto sm:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                33vw"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
